/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IBiArrowLeftRight: typeof import('~icons/bi/arrow-left-right')['default']
    IBiArrowRightCircle: typeof import('~icons/bi/arrow-right-circle')['default']
    IBiBoxArrowInRight: typeof import('~icons/bi/box-arrow-in-right')['default']
    IBiBoxArrowUpRight: typeof import('~icons/bi/box-arrow-up-right')['default']
    IBiCheck: typeof import('~icons/bi/check')['default']
    IBiCheck2All: typeof import('~icons/bi/check2-all')['default']
    IBiCheckCircle: typeof import('~icons/bi/check-circle')['default']
    IBiChevronUp: typeof import('~icons/bi/chevron-up')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiEmojiSmile: typeof import('~icons/bi/emoji-smile')['default']
    IBiExclamation: typeof import('~icons/bi/exclamation')['default']
    IBiFileEarmark: typeof import('~icons/bi/file-earmark')['default']
    IBiListOl: typeof import('~icons/bi/list-ol')['default']
    IBiPen: typeof import('~icons/bi/pen')['default']
    IBiPencil: typeof import('~icons/bi/pencil')['default']
    IBiPencilSquare: typeof import('~icons/bi/pencil-square')['default']
    IBiPlus: typeof import('~icons/bi/plus')['default']
    IBiPlusSquare: typeof import('~icons/bi/plus-square')['default']
    IBiQuestionCircle: typeof import('~icons/bi/question-circle')['default']
    IBiTrash: typeof import('~icons/bi/trash')['default']
    IBiXCircle: typeof import('~icons/bi/x-circle')['default']
    IBiXCircleFill: typeof import('~icons/bi/x-circle-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
