<template>
    <div>
        <client-only>
            <div>
                <UiTableInput
                    :label="$t('registration.CompanyTaxNumber')"
                    :placeholder="$t('registration.CompanyTaxNumber')"
                    name="companyTaxNumber"
                    type="text"
                />
                <UiTableInput
                    :label="$t('registration.CompanyPhoneNumber')"
                    :placeholder="$t('registration.CompanyPhoneNumber')"
                    name="companyPhoneNumber"
                    type="tel"
                />
                <UiTableInput
                    :label="$t('registration.CompanyEmail')"
                    :placeholder="$t('registration.CompanyEmail')"
                    type="email"
                    name="companyEmail"
                />
                <UiTableInput
                    :label="$t('registration.CompanyAddress')"
                    :placeholder="$t('registration.CompanyAddress')"
                    name="companyAddress"
                    type="text"
                />
                <UiTableInput
                    :label="$t('registration.PostalAddress')"
                    :placeholder="$t('registration.PostalAddress')"
                    name="postalAddress"
                    type="text"
                />
            </div>
        </client-only>
    </div>
</template>
